<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>

        <!--    Package Configurations -->
        <PackageId>Nullnes.Labs.Result.Errors</PackageId>
        <Description>Optional error types for Nullnes.Labs.Result.* ecosystem. Framework agnostic and lean.</Description>
        <PackageProjectUrl>https://github.com/Rennasccenth/nullnes.result</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Rennasccenth/nullnes.result</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Authors>Felipe Nunes</Authors>
        <Company>Nullnes.Labs</Company>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageTags>Errors;Result; Railway Oriented Programming; ROP; Error Handling; Monadic;</PackageTags>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nullnes.Labs.Result.Abstractions\Nullnes.Labs.Result.Abstractions.csproj" />
    </ItemGroup>

</Project>
