name: Build Solution

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env: 
  DOTNET_VERSION: 9.0.x
  DOTNET_CONFIGURATION: Release
  
  # Testing Variables
  TESTS_VERBOSITY_LEVEL: normal

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: ⚙️ Setup .NET ️
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: 🔎 Restore dependencies
      run: dotnet restore
    
    - name: 🔨 Build
      run: dotnet build --no-restore --configuration ${{ env.DOTNET_CONFIGURATION }}

    - name: 🙏🏽 Run Unit Tests
      run: dotnet test --configuration ${{ env.DOTNET_CONFIGURATION }} --verbosity ${{ env.TESTS_VERBOSITY_LEVEL }}
