name: Publish Entry

on:
  push:
    branches:
      - feature/publish-into-nuget

env:
  DOTNET_VERSION: &dotnet_version 9.0.x
  DOTNET_CONFIGURATION: &dotnet_configuration Release
  VERBOSITY_LEVEL: &verbosity_level normal
  NUGET_PACKAGES_FOLDER: &nuget_packages_folder ./nupkgs

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      dotnet-version: *dotnet_version
      dotnet-configuration: *dotnet_configuration
      verbosity: *verbosity_level
      should-include-tests-artifacts: true
      upload-artifacts-name: "some-cool-name"

  tests:
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      dotnet-version: *dotnet_version
      dotnet-configuration: *dotnet_configuration
      verbosity: *verbosity_level
      upload-artifacts-name: "some-cool-name"

#  pack:
#    needs: build
#    uses: ./.github/workflows/reusable-pack.yml
#    with:
#      configuration: ${{ env.CONFIGURATION }}
#      verbosity: ${{ env.VERBOSITY }}
#      output-folder: ${{ env.OUTPUT_FOLDER }}
#      environment: Integration  # <- Can be dynamic
#
#  push:
#    needs: pack
#    uses: ./.github/workflows/reusable-push.yml
#    with:
#      source-url: https://int.nugettest.org
#      output-folder: ${{ env.OUTPUT_FOLDER }}
#    secrets:
#      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
#    environment: Integration