name: Publish Packages

on:
  push: 
    branches:
      - feature/publish-into-nuget

env:
  DOTNET_VERSION: 9.0.x
  DOTNET_CONFIGURATION: Release
  
  LOGS_VERBOSITY_LEVEL: normal
  
  # Transient
  BUILD_OUTPUT_NAME: build-name

  # NUGET
  NUGET_PACKAGES_FOLDER: './nupkgs'
#  NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json
  NUGET_SOURCE_URL: https://int.nugettest.org
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ✓ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Setup .NET ️
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🔎 Restore dependencies
        run: dotnet restore

      - name: 🔨 Build
        run: dotnet build --no-restore --configuration ${{ env.DOTNET_CONFIGURATION }}

      - name: 📦 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_OUTPUT_NAME }}
          path: |
            src/**/bin/
            src/**/obj/
            tests/**/bin/
            tests/**/obj/

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: ✓ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Setup .NET ️
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 📦 Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_OUTPUT_NAME }}

      - name: 🧪 Run Unit Tests
        run: dotnet test --no-build --configuration ${{ env.DOTNET_CONFIGURATION }} --verbosity ${{ env.LOGS_VERBOSITY_LEVEL }}

  publish:
    name: Publish to NuGet
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: ✓ Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: ⚙️ Setup .NET ️
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🚀 Find and Pack NuGet packages
        shell: bash
        run: |
          chmod +x ./github/scripts/build_and_pack_projects.sh
          ./github/scripts/build_and_pack_projects.sh --configuration ${{ env.DOTNET_CONFIGURATION }} --verbosity ${{ env.LOGS_VERBOSITY_LEVEL}} --pack-output ${{ env.NUGET_PACKAGES_FOLDER }}

      - name: 🚀 Publish NuGet packages
        run: dotnet nuget push "${{ env.NUGET_PACKAGES_FOLDER}}/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ env.NUGET_SOURCE_URL }} --skip-duplicate
