name: Publish Entry

on:
  push:
    branches:
      - feature/publish-into-nuget

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      dotnet-configuration: ${{ vars.DOTNET_CONFIGURATION }}
      verbosity: ${{ vars.VERBOSITY_LEVEL }}
      should-include-tests-artifacts: true
      upload-build-artifacts-name: build-artifacts-upload-name
      upload-test-build-artifacts-name: test-artifacts-upload-name

  tests:
    needs: build
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      dotnet-version: ${{ vars.DOTNET_VERSION }}
      dotnet-configuration: ${{ vars.DOTNET_CONFIGURATION }}
      verbosity: ${{ vars.VERBOSITY_LEVEL }}
      upload-build-artifacts-name: ${{ needs.build.outputs.upload-build-artifacts-name }}
      upload-test-build-artifacts-name: ${{ needs.build.outputs.upload-test-build-artifacts-name }}

#  pack:
#    needs: build
#    uses: ./.github/workflows/reusable-pack.yml
#    with:
#      configuration: ${{ env.CONFIGURATION }}
#      verbosity: ${{ env.VERBOSITY }}
#      output-folder: ${{ env.OUTPUT_FOLDER }}
#      environment: Integration  # <- Can be dynamic
#
#  push:
#    needs: pack
#    uses: ./.github/workflows/reusable-push.yml
#    with:
#      source-url: https://int.nugettest.org
#      output-folder: ${{ env.OUTPUT_FOLDER }}
#    secrets:
#      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
#    environment: Integration