name: Publish Packages

on:
  push: 
    branches:
      - feature/publish-into-nuget

env:
  DOTNET_VERSION: 9.0.x
  DOTNET_CONFIGURATION: Release
  
  # Nuget
  
  # Testing Variables
  TESTS_VERBOSITY_LEVEL: normal
  
  # Transient
  BUILD_OUTPUT_NAME: build-name
  NUGET_PACKAGES_FOLDER: './nupkgs'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ⚙️ Setup .NET ️
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 🔎 Restore dependencies
        run: dotnet restore

      - name: 🔨 Build
        run: dotnet build --no-restore --configuration ${{ env.DOTNET_CONFIGURATION }}

      - name: 📦 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_OUTPUT_NAME }}
          path: |
            src/**/bin/
            src/**/obj/
            tests/**/bin/
            tests/**/obj/

  test:
    name: Run Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ⚙️ Setup .NET ️
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 📦 Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_OUTPUT_NAME }}

      - name: 🧪 Run Unit Tests
        run: dotnet test --no-build --configuration ${{ env.DOTNET_CONFIGURATION }} --verbosity ${{ env.TESTS_VERBOSITY_LEVEL }}

  publish:
    name: Publish to NuGet
    needs: test
    runs-on: ubuntu-latest
    # Only run on main branch, not on PRs
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: ⚙️ Setup .NET ️
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 📦 Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.BUILD_OUTPUT_NAME }}

      - name: 🚀 Find and pack NuGet packages
        run: |
          mkdir -p ${{ env.NUGET_PACKAGES_FOLDER}}
          for project in $(find ./src -name "*.csproj")
          do
            echo "Packing $project"
            dotnet pack $project --no-build --configuration ${{ env.DOTNET_CONFIGURATION }} --output ${{ env.NUGET_PACKAGES_FOLDER}}/$project
          done

      - name: 🚀 Publish NuGet packages
        run: dotnet nuget push "${{ env.NUGET_PACKAGES_FOLDER}}/**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
