name: Pack

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
        default: 9.0.x
        description: Defines the .NET version to be used for pack the projects
      dotnet-configuration:
        required: true
        default: Release
        type: string
        description: Defines the Configuration of the pack command
      upload-build-artifacts-name:
        required: true
        type: string
        default: build-artifacts-name
        description: The name of the artifacts upload step wheres a build workflow uploaded the build artifacts
      nuget-packages-output-folder:
        required: true
        default: ./nupkgs
        type: string
      verbosity:
        required: false
        type: string
        default: normal
        description: Defines the verbosity level of the pack command
      environment:
        required: false
        default: Integration
        type: string
        description: The environment of the running context, this defines the strategies related to version publish and naming

jobs:
  detect-projects:
    name: 🔎 Detect projects to Pack
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: ✓ Shallow Checkout
        uses: actions/checkout@v4

      - name: ✅ Set projects matrix
        run: |
          projects=$(find ./src -name '*.csproj' | jq --raw-input --slurp --compact-output 'split("\n") | map(select(length > 0))')
          echo $projects
          echo "matrix=$projects" >> $GITHUB_OUTPUT

  pack:
    name: 📦 Pack detected projects
    runs-on: ubuntu-latest
    needs: detect-projects
    strategy:
      matrix:
        project: ${{ fromJson(needs.detect-projects.outputs.matrix) }}
    steps:
      - name: ✓ Deep Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.upload-build-artifacts-name }}
          path: ./src
      
      - name: ⚙️ Setup .NET ️
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: 📦 Pack Project
        shell: bash
        run: |
          VERSION=$(nbgv get-version -p "$(dirname ${{ matrix.project }})" --variable Version)
          dotnet pack ${{ matrix.project }} \
            --configuration ${{ inputs.dotnet-configuration }} \
            --output ${{ inputs.nuget-packages-output-folder }} \
            /p:Version=$VERSION

#          chmod +x ./.github/scripts/pack_projects.sh
#
#          ./.github/scripts/pack_projects.sh \ 
#            --configuration ${{ inputs.dotnet-version }} \
#            --verbosity ${{ inputs.verbosity }} \
#            --pack-output ${{ inputs.nuget-packages-output-folder }}
 
#         if [[ "${{ inputs.environment }}" == "Integration" ]]; then
#            echo "Packing with integration-specific logic..."
#            ./.github/scripts/build_and_pack_projects.sh \
#              --configuration ${{ inputs.configuration }} \
#              --verbosity ${{ inputs.verbosity }} \
#              --pack-output ${{ inputs.nuget-packages-output-folder }} \
#              --include-prerelease
#          else
#            echo "Standard packing..."
#            ./.github/scripts/build_and_pack_projects.sh \
#              --configuration ${{ inputs.configuration }} \
#              --verbosity ${{ inputs.verbosity }} \
#              --pack-output ${{ inputs.nuget-packages-output-folder }}
#          fi