name: Build .NET Projects
run-name: Build projects

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
        default: 9.0.x
        description: Defines the .NET version to be used for build the projects 
      dotnet-configuration:
        required: false
        default: Release
        type: string
        description: Defines the Configuration of the build command
      verbosity:
        required: false
        type: string
        default: normal
        description: Defines the verbosity level of the build command
      should-include-tests-artifacts:
        required: false
        type: boolean
        default: true
        description: Instructs the build workflow when to share the test projects artifacts
      upload-build-artifacts-name:
        required: false
        type: string
        default: build-artifacts-name
        description: The name of the artifacts upload step wheres the workflow upload the build artifacts
      upload-test-build-artifacts-name:
        required: false
        type: string
        default: test-build-artifacts-name
        description: The name of the artifacts upload step wheres the workflow upload the build artifacts

    outputs:
      upload-build-artifacts-name:
        description: Name of build artifact, use it to download the artifacts
        value: ${{ jobs.build.outputs.upload-build-artifacts-name }}
      upload-test-build-artifacts-name:
        description: Name of test build artifact, use it to download the artifacts
        value: ${{ jobs.build.outputs.upload-test-build-artifacts-name }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      upload-build-artifacts-name: ${{ inputs.upload-build-artifacts-name }}
      upload-test-build-artifacts-name: ${{ inputs.upload-test-build-artifacts-name }}
    steps:
      - name: ✓ Deep Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ⚙️ Setup .NET ️
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: 🔎 Restore dependencies
        run: dotnet restore

      - name: 🔨 Build
        run: dotnet build --no-restore --configuration ${{ inputs.dotnet-configuration }} --verbosity ${{ inputs.verbosity }}

      - name: 📦 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.upload-build-artifacts-name }}
          path: |
             src/**/bin/
             src/**/obj/

      - name: 📦 Upload test build artifacts
        if: inputs.should-include-tests-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.upload-test-build-artifacts-name }}
          path: |
            tests/**/bin/
            tests/**/obj/